# -*- coding: utf-8 -*-
"""kpca_conversation_self_awareness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9ouIlhRaTvR8anQfdt7ZYaXS1J-aRq5
"""

!pip install -q datasets scikit-learn seaborn

import numpy as np
import torch
from datasets import load_dataset
from sklearn.decomposition import KernelPCA
import matplotlib.pyplot as plt
import seaborn as sns

dataset_name = "shiv96/convsersations_rude_llama3.2-1B-it_large"
ds = load_dataset(dataset_name, split="train")

print(len(ds))
print(ds.column_names)

def extract_layer_activations(dataset, layer_id):
    """
    Returns:
        X: (N, D) numpy array
        y: (N,) labels in {-1, +1}
    """
    layer_key = f"model.layers.{layer_id}.resid"

    X = np.stack([np.array(x, dtype=np.float32) for x in dataset[layer_key]])
    y = np.array(dataset["label"], dtype=np.int64)

    return X, y

X, y = extract_layer_activations(ds, layer_id=10)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("labels:", np.unique(y))

k = 50
epsilon = 1e-2

kpca = KernelPCA(
    n_components=k,
    kernel="poly",
    degree=3,
    gamma=1.0 / X.shape[1],
    coef0=1.0,
    fit_inverse_transform=True
)

Z = kpca.fit_transform(X)
print("Z shape:", Z.shape)

Z_pos = Z[y == 1]
Z_neg = Z[y == -1]

mu_pos = Z_pos.mean(axis=0)
mu_neg = Z_neg.mean(axis=0)

mu_pos_x = X[y == 1].mean(axis=0)
mu_neg_x = X[y == -1].mean(axis=0)

v_global = mu_pos_x - mu_neg_x
v_global = v_global / (np.linalg.norm(v_global) + 1e-8)

cosines = []

for i in range(len(X)):
    z_i = Z[i]


    if y[i] == 1:
        u_i = mu_neg - z_i
    else:
        u_i = mu_pos - z_i

    norm = np.linalg.norm(u_i)
    if norm < 1e-8:
        continue
    u_i = u_i / norm


    z_i_prime = z_i + epsilon * u_i


    x_i_prime = kpca.inverse_transform(z_i_prime.reshape(1, -1))[0]

    # point-wise displacement in activation space
    u_i_prime = x_i_prime - X[i]
    u_i_prime = u_i_prime / (np.linalg.norm(u_i_prime) + 1e-8)

    cosines.append(np.dot(u_i_prime, v_global))

cosines = np.array(cosines)

print("Local ε-step kPCA steering:")
print(f"  mean cosine = {cosines.mean():.4f}")
print(f"  std  cosine = {cosines.std():.4f}")
print(f"  num points  = {len(cosines)}")

plt.figure(figsize=(6,4))
sns.kdeplot(cosines, linewidth=2)
plt.axvline(0, color="gray", linestyle="--", alpha=0.5)
plt.xlabel("Cosine similarity to global mean-difference")
plt.ylabel("Density")
plt.title("Local ε-step kPCA steering (k=50, poly kernel)")
plt.tight_layout()
plt.show()