# -*- coding: utf-8 -*-
"""kpca_conversation_self_awareness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9ouIlhRaTvR8anQfdt7ZYaXS1J-aRq5
"""

!pip install -q datasets scikit-learn seaborn

import numpy as np
import torch
from datasets import load_dataset
from sklearn.decomposition import KernelPCA
import matplotlib.pyplot as plt
import seaborn as sns

dataset_name = "shiv96/convsersations_self_awareness_general_llama3.2-1B-it_large"
ds = load_dataset(dataset_name, split="train")

print(len(ds))
print(ds.column_names)

def extract_layer_activations(dataset, layer_id):
    """
    Returns:
        X: (N, D) numpy array
        y: (N,) labels in {-1, +1}
    """
    layer_key = f"model.layers.{layer_id}.resid"

    X = np.stack([np.array(x, dtype=np.float32) for x in dataset[layer_key]])
    y = np.array(dataset["label"], dtype=np.int64)

    return X, y

X, y = extract_layer_activations(ds, layer_id=10)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("labels:", np.unique(y))

k = 50
epsilon = 1e-2

kpca = KernelPCA(
    n_components=k,
    kernel="poly",
    degree=3,
    gamma=1.0 / X.shape[1],
    coef0=1.0,
    fit_inverse_transform=True
)

Z = kpca.fit_transform(X)
print("Z shape:", Z.shape)

Z_pos = Z[y == 1]
Z_neg = Z[y == -1]

mu_pos = Z_pos.mean(axis=0)
mu_neg = Z_neg.mean(axis=0)

mu_pos_x = X[y == 1].mean(axis=0)
mu_neg_x = X[y == -1].mean(axis=0)

v_global = mu_pos_x - mu_neg_x
v_global = v_global / (np.linalg.norm(v_global) + 1e-8)

u_primes = []

for i in range(len(X)):
    z_i = Z[i]

    if y[i] == 1:
        u_i = mu_neg - z_i
    else:
        u_i = mu_pos - z_i

    norm = np.linalg.norm(u_i)
    if norm < 1e-8:
        continue
    u_i = u_i / norm

    z_i_prime = z_i + epsilon * u_i
    x_i_prime = kpca.inverse_transform(z_i_prime.reshape(1, -1))[0]

    u_i_prime = x_i_prime - X[i]
    norm_u = np.linalg.norm(u_i_prime)
    if norm_u < 1e-8:
        continue
    u_i_prime = u_i_prime / norm_u

    u_primes.append(u_i_prime)

u_primes = np.stack(u_primes)

# e1: global steering direction
e1 = v_global / (np.linalg.norm(v_global) + 1e-8)

# remove e1 component from u_i'
residuals = u_primes - (u_primes @ e1)[:, None] * e1[None, :]

# PCA on residuals to get dominant spread direction
U, S, Vt = np.linalg.svd(residuals, full_matrices=False)
e2 = Vt[0]

proj_1 = u_primes @ e1
proj_2 = u_primes @ e2

plt.figure(figsize=(6,6))
plt.scatter(proj_1, proj_2, s=5, alpha=0.4)
plt.axhline(0, color="gray", linestyle="--", alpha=0.5)
plt.axvline(0, color="gray", linestyle="--", alpha=0.5)

plt.xlabel("Projection onto global steering direction")
plt.ylabel("Projection onto dominant orthogonal direction")
plt.title("2D projection of point-wise kPCA steering displacements")
plt.tight_layout()
plt.show()

print(ds.column_names)

import numpy as np
from datasets import load_dataset
from sklearn.decomposition import KernelPCA
import matplotlib.pyplot as plt
import seaborn as sns


dataset_name = "shiv96/convsersations_rude_llama3.2-1B-it_large"
ds = load_dataset(dataset_name, split="train")

print("Dataset size:", len(ds))
print("Columns:", ds.column_names)


def extract_layer_activations(dataset, layer_id):
    layer_key = f"model.layers.{layer_id}.resid"
    X = np.stack([np.array(x, dtype=np.float32) for x in dataset[layer_key]])
    y = np.array(dataset["label"], dtype=np.int64)
    return X, y

layer_id = 10
X, y = extract_layer_activations(ds, layer_id)

topics = np.array(ds["topic"])
subtopics = np.array(ds["subtopic"])

responses = np.array(ds["response"])


print("X shape:", X.shape)
print("Labels:", np.unique(y))


k = 50
epsilon = 1e-2

kpca = KernelPCA(
    n_components=k,
    kernel="poly",
    degree=3,
    gamma=1.0 / X.shape[1],
    coef0=1.0,
    fit_inverse_transform=True
)

Z = kpca.fit_transform(X)

Z_pos = Z[y == 1]
Z_neg = Z[y == -1]

mu_pos = Z_pos.mean(axis=0)
mu_neg = Z_neg.mean(axis=0)


mu_pos_x = X[y == 1].mean(axis=0)
mu_neg_x = X[y == -1].mean(axis=0)

v_global = mu_pos_x - mu_neg_x
v_global = v_global / (np.linalg.norm(v_global) + 1e-8)


u_primes = []
topic_kept = []
subtopic_kept = []
ab_kept = []


for i in range(len(X)):
    z_i = Z[i]

    if y[i] == 1:
        u_i = mu_neg - z_i
    else:
        u_i = mu_pos - z_i

    norm = np.linalg.norm(u_i)
    if norm < 1e-8:
        continue
    u_i = u_i / norm

    z_i_prime = z_i + epsilon * u_i
    x_i_prime = kpca.inverse_transform(z_i_prime.reshape(1, -1))[0]

    u_i_prime = x_i_prime - X[i]
    norm_u = np.linalg.norm(u_i_prime)
    if norm_u < 1e-8:
        continue
    u_i_prime = u_i_prime / norm_u

    u_primes.append(u_i_prime)
    topic_kept.append(topics[i])
    subtopic_kept.append(subtopics[i])
    ab_kept.append(responses[i])

u_primes = np.stack(u_primes)
topic_kept = np.array(topic_kept)
subtopic_kept = np.array(subtopic_kept)
ab_kept = np.array(ab_kept)


print("Kept points:", len(u_primes))


e1 = v_global


residuals = u_primes - (u_primes @ e1)[:, None] * e1[None, :]

U, S, Vt = np.linalg.svd(residuals, full_matrices=False)
e2 = Vt[0]

# 2D projection
proj_1 = u_primes @ e1
proj_2 = u_primes @ e2

def extract_ab(resp):
    if "A" in resp:
        return "A"
    elif "B" in resp:
        return "B"
    else:
        return "Other"

ab_simple = np.array([extract_ab(r) for r in ab_kept])


# Plot: colored by topic
plt.figure(figsize=(6,6))
sns.scatterplot(
    x=proj_1,
    y=proj_2,
    hue=topic_kept,
    s=10,
    alpha=0.6
)
plt.axhline(0, color="gray", linestyle="--", alpha=0.3)
plt.axvline(0, color="gray", linestyle="--", alpha=0.3)
plt.xlabel("Projection onto global steering direction")
plt.ylabel("Projection onto dominant orthogonal direction")
plt.title("2D projection of point-wise kPCA steering (colored by topic)")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# Plot: colored by subtopic
plt.figure(figsize=(6,6))
sns.scatterplot(
    x=proj_1,
    y=proj_2,
    hue=subtopic_kept,
    s=10,
    alpha=0.6
)
plt.axhline(0, color="gray", linestyle="--", alpha=0.3)
plt.axvline(0, color="gray", linestyle="--", alpha=0.3)
plt.xlabel("Projection onto global steering direction")
plt.ylabel("Projection onto dominant orthogonal direction")
plt.title("2D projection of point-wise kPCA steering (colored by subtopic)")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()


plt.figure(figsize=(6,6))
sns.scatterplot(
    x=proj_1,
    y=proj_2,
    hue=ab_simple,
    s=10,
    alpha=0.6
)

plt.axhline(0, color="gray", linestyle="--", alpha=0.3)
plt.axvline(0, color="gray", linestyle="--", alpha=0.3)

plt.xlabel("Projection onto global steering direction")
plt.ylabel("Projection onto dominant orthogonal direction")
plt.title("2D projection of point-wise kPCA steering (colored by A/B response)")
plt.legend(title="Response", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

import re

def extract_answer_letter(resp):
    """
    Try to extract answer letter from response text.
    Returns 'A', 'B', 'C', 'D' or None.
    """
    if resp is None:
        return None
    m = re.search(r"\(([A-D])\)", resp)
    if m:
        return m.group(1)
    return None

answers = [extract_answer_letter(r) for r in ds["response"]]
answers = np.array(answers)

mask_ab = np.isin(answers, ["A", "B"])

from sklearn.decomposition import PCA

U2 = PCA(n_components=2).fit_transform(u_primes)

import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))

for letter, color in zip(["A", "B"], ["tab:blue", "tab:orange"]):
    idx = (answers[:len(U2)] == letter)
    plt.scatter(
        U2[idx, 0],
        U2[idx, 1],
        s=8,
        alpha=0.6,
        label=f"Answer {letter}",
        color=color
    )

plt.xlabel("PC 1")
plt.ylabel("PC 2")
plt.legend()
plt.title("2D projection colored by answer letter")
plt.tight_layout()
plt.show()

print(ds.column_names)

responses = np.array(ds["response"])
labels = np.array(ds["label"])

def is_A_resp(r):
    r = r.strip()
    return r == "A" or r == "(A)" or r.startswith("A")

def is_B_resp(r):
    r = r.strip()
    return r == "B" or r == "(B)" or r.startswith("B")

is_A = np.array([is_A_resp(r) for r in responses])
is_B = np.array([is_B_resp(r) for r in responses])

print("Total samples:", len(labels))
print("A responses:", is_A.sum())
print("B responses:", is_B.sum())

print("\nLabel distribution:")
print("Positive labels:", (labels == 1).sum())
print("Negative labels:", (labels == -1).sum())

print("\nCross-tab:")
print("A & positive:", np.sum(is_A & (labels == 1)))
print("A & negative:", np.sum(is_A & (labels == -1)))
print("B & positive:", np.sum(is_B & (labels == 1)))
print("B & negative:", np.sum(is_B & (labels == -1)))